//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCH.Resources.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ah.
        /// </summary>
        public static string Ah {
            get {
                return ResourceManager.GetString("Ah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anal.
        /// </summary>
        public static string Anal {
            get {
                return ResourceManager.GetString("Anal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ass.
        /// </summary>
        public static string Ass {
            get {
                return ResourceManager.GetString("Ass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bah.
        /// </summary>
        public static string Bah {
            get {
                return ResourceManager.GetString("Bah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boy|boy next door.
        /// </summary>
        public static string BoyNextDoor {
            get {
                return ResourceManager.GetString("BoyNextDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comming|cumming|coming|come in.
        /// </summary>
        public static string Cumming {
            get {
                return ResourceManager.GetString("Cumming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deep.
        /// </summary>
        public static string Deep {
            get {
                return ResourceManager.GetString("Deep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deep dark fantasies.
        /// </summary>
        public static string DeepDarkFantasies {
            get {
                return ResourceManager.GetString("DeepDarkFantasies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dont|don&apos;t.
        /// </summary>
        public static string Dont {
            get {
                return ResourceManager.GetString("Dont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t stop|dont stop.
        /// </summary>
        public static string DontStop {
            get {
                return ResourceManager.GetString("DontStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dungeon master.
        /// </summary>
        public static string DungeonMaster {
            get {
                return ResourceManager.GetString("DungeonMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuck.
        /// </summary>
        public static string Fuck {
            get {
                return ResourceManager.GetString("Fuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full master.
        /// </summary>
        public static string FullMaster {
            get {
                return ResourceManager.GetString("FullMaster", resourceCulture);
            }
        }
    }
}
