//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCH.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice added. The duration is about {0:mm\:ss\:ff}. Max duration is {1:mm\:ss\:ff}.
        /// </summary>
        internal static string AfterVoiceAddedMessage {
            get {
                return ResourceManager.GetString("AfterVoiceAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to settings.
        /// </summary>
        internal static string BackToSettings {
            get {
                return ResourceManager.GetString("BackToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice creation was cancelled..
        /// </summary>
        internal static string CancelAlert {
            get {
                return ResourceManager.GetString("CancelAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose settings to change.
        /// </summary>
        internal static string ChooseSettingsToChange {
            get {
                return ResourceManager.GetString("ChooseSettingsToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was not found.
        /// </summary>
        internal static string FileWasNotFound {
            get {
                return ResourceManager.GetString("FileWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ♂RIGHT♂ voice.
        /// </summary>
        internal static string GetCurrentVoice {
            get {
                return ResourceManager.GetString("GetCurrentVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello ♂{0}♂. This is a bot to create ♂Right♂ voice mems. In order to create mem use command /create..
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageSelected {
            get {
                return ResourceManager.GetString("LanguageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More.
        /// </summary>
        internal static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Prev.
        /// </summary>
        internal static string LoadPrev {
            get {
                return ResourceManager.GetString("LoadPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me a voice or choose from existing.
        /// </summary>
        internal static string SendMeVoice {
            get {
                return ResourceManager.GetString("SendMeVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} to {1} mems.
        /// </summary>
        internal static string StateAlertMessage {
            get {
                return ResourceManager.GetString("StateAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice {0} was added. It may takes some time..
        /// </summary>
        internal static string VoiceAddedAlert {
            get {
                return ResourceManager.GetString("VoiceAddedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♂RIGHT♂ Voice by @GachiBillieVoice_bot.
        /// </summary>
        internal static string VoiceCaption {
            get {
                return ResourceManager.GetString("VoiceCaption", resourceCulture);
            }
        }
    }
}
